http:
  routers:
    rpc-server:
      rule: "Host(`{{env "RPC_DOMAIN"}}`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "rpc-ratelimit"
      tls:
        certResolver: "le-ssl"
      service: "rpc-server"

    api-server:
      rule: "Host(`{{env "API_DOMAIN"}}`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "rpc-ratelimit"
      tls:
        certResolver: "le-ssl"
      service: "api-server"

  services:
    rpc-server:
      loadBalancer:
        servers:
          - url: "http://{{env "HOST"}}:{{env "RPC_PORT"}}"

    api-server:
      loadBalancer:
        servers:
          - url: "http://{{env "HOST"}}:{{env "API_PORT"}}"

  middlewares:
    rpc-ratelimit:
      rateLimit:
        average: "{{env "RATE_LIMIT_AVERAGE"}}"
        burst: "{{env "RATE_LIMIT_BURST"}}"
        period: "{{env "RATE_LIMIT_PERIOD"}}"
        sourceCriterion:
          ipStrategy:
            depth: "{{env "RATE_LIMIT_IP_DEPTH"}}"
